controllers/TextController.php
<?php

namespace app\controllers;

use app\models\Section;
use Yii;
use app\models\Text;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use app\models\Comments;
use app\models\ContactForm;
use app\models\Watch;
use app\models\VoteText;
use yii\helpers\Url;

class TextController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Text::find()->where(['moderation' => Text::STATUS_PUBLISH])->orderBy('date DESC'),
            'pagination' => [
                'pageSize' => 10,
                'defaultPageSize' => 10,
            ],
        ]);
        return $this->render('index', [
            'listDataProvider' => $dataProvider
        ]);
    }

    public function actionView($id)
    {
        $model = Text::find()->where([
            'id' => $id,
            'moderation' => Text::STATUS_PUBLISH
        ])->one();

        if ($model === null) {
            throw new NotFoundHttpException;
        }

        // TODO Сервиска кучерергэ
        $model->updateCounters(['watch' => 1]);

        $modelComments = new Comments();
        $modelComments->text_id = $model->id;
        $modelComments->date = time();
        $modelComments->user_id = Yii::$app->user->getId();
        if ($modelComments->load(Yii::$app->request->post()) && $modelComments->save()) {
            return $this->refresh();
        }

        $allComments = Comments::find()->with('user')->where(['text_id' => $id])->all();

        return $this->render('view', [
            'model' => $model,
            'modelComments' => $modelComments,
            'comments' => $allComments,
        ]);
    }

    /**
     *
     * Add vote to text
     *
     * @param string $type
     * @param int $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionVote(string $type, int $id)
    {
        $user = Yii::$app->user->getId();

        if (Yii::$app->user->isGuest) {
            return $this->render('info', [
                'alert' => 'warning',
                'message' => 'Бары тик <a href=' . Url::to(['/user/user/signup']) . ' class="alert-link">теркәлгән</a>
                һәм <a href="' . Url::to(['/user/user/login']) . '" class="alert-link">авторизация</a> үткән кулланучылар
                 гына тавыш бирә ала.',
                'title' => 'Бары тик теркәлгән һәм авторизация үткән кулланучылар гына тавыш бирә ала',
            ]);
        }

        $model = Text::find()->where([
            'id' => $id,
            'moderation' => Text::STATUS_PUBLISH
        ])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        $vote = VoteText::find()->where([
            'text_id' => $id,
            'user_id' => $user,
        ])->one();


        if ($vote === null) {
            $newVote = new VoteText();
            $newVote->text_id = $id;
            $newVote->user_id = $user;
            $newVote->save();

            $update = (($type == 'rox') ? 1 : (($type == 'sox') ? '-1' : 0));
            $model->updateCounters(['rating' => $update]);
        } else {
            return $this->render('info', [
                'alert' => 'warning',
                'message' => 'Сез инде бу текстка тавыш бирдегез!'
            ]);
        }

        return $this->redirect(['text/view', 'id' => $id]);

    }

    public function actionOrder()
    {
        throw new NotFoundHttpException;
        return $this->render('order');
    }

    public function actionAdd()
    {
        $model = new Text();

        $sections = Section::find()->all();
        $sections = ArrayHelper::map($sections, 'id', 'name');

        $ip = ip2long(Yii::$app->getRequest()->getUserIP());
        $model->ip = $ip;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->render('info', [
                'alert' => 'success',
                'message' => 'Сезнең текст модерацияга жибәрелде. Модерация уткәч сайтта чыгыр. Рәхмәт!'
            ]);
        }

        return $this->render('add',[
            'model' => $model,
            'section' => $sections
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSitemap()
    {
        return $this->render('sitemap', [
            'text' => Text::find()->where(['moderation' => Text::STATUS_PUBLISH])->all()
        ]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    <?= Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Баш бит', 'url' => ['/text/index']],
            ['label' => 'Заказ биру', 'url' => ['/text/order']],
            ['label' => 'Өстәү', 'url' => ['/text/add']],
            ['label' => 'Сайт турында', 'url' => ['/text/about']],
            ['label' => 'Элемтә', 'url' => ['/site/contact']],
        ],
    ]);?>
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/text.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\widgets\Menu;
use app\components\LastCommentsWidget;
use app\components\LikeTextWidget;
use app\components\WatchWidget;
use app\components\StatisticsWidget;
use app\components\LastNewsWidget;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <?= Html::csrfMetaTags() ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    <?php $this->beginBody() ?>

    <!-- Yandex.Metrika counter -->
    <script>
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter26013825 = new Ya.Metrika({
                        id:26013825,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true,
                        trackHash:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/26013825" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-87489630-1', 'auto');
      ga('send', 'pageview');

    </script>

    <!-- header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <a href="/" class="logo pull-left"><img src="/img/logo.png" alt="logo"></a>
                    <div class="search pull-right">
                        <form>
                            <input type="text" name="text">
                            <button>Эзлэу</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header -->

    <!-- menu -->

    <?php

    $menuItems = [
        ['label' => 'Баш бит', 'url' => ['/text/index']],
        ['label' => 'Сайт турында', 'url' => ['/text/about']]
    ];

    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Теркәлү', 'url' => ['/user/user/signup']];
        $menuItems[] = ['label' => 'Керү', 'url' => ['/user/user/login']];
    } else {
        /*$menuItems[] = ['label' => 'Заказ биру', 'url' => ['/text/order']];*/
        $menuItems[] = ['label' => 'Өстәү', 'url' => ['/text/add']];
        $menuItems[] = [
            'label' => 'Чыгу [' . Yii::$app->user->identity['username'] . ']',
            'url' => ['/user/user/logout'],
            'linkOptions' => ['data-method' => 'post'],
        ];
    }
    ?>

    <nav>
        <?= Menu::widget([
            'options' => ['class' => 'menu center-block hidden-xs'],
            'items' => $menuItems
        ]);?>
    </nav>
    <!-- menu -->

    <!-- content -->
    <div class="content">
        <div class="container bg">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <?= $content ?>
                </div>

                <!-- sidebar -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 sidebar">

                    <!-- last news -->
                    <?= LastNewsWidget::widget() ?>
                    <!-- last news -->

                    <!-- read -->
                    <?= WatchWidget::widget() ?>
                    <!-- read -->

                    <!-- like -->
                    <?= LikeTextWidget::widget() ?>
                    <!-- like -->

                    <!-- last comments -->
                    <?= LastCommentsWidget::widget() ?>
                    <!-- last comments -->

                    <!-- statistics -->
                    <?= StatisticsWidget::widget() ?>
                    <!-- statistics -->

                </div>
                <!-- sidebar -->

            </div>
        </div>
    </div>
    <!-- content -->

    <footer>
        <div class="container">
            <div class="col-md-12">
                <div class="text-center">
                    ©2012-<?=date('Y');?> insha.ru Барлык мәгълүмәт интернет челтәреннән табылды.
                    <a  href="<?= Url::toRoute(['/text/sitemap']) ?>">Барлык иншалар.</a>
                </div>
            </div>
        </div>
    </footer>

    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>