models/Text.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "text".
 *
 * @property integer $id
 * @property integer $date
 * @property integer $rating
 * @property string $title
 * @property string $text
 * @property integer $moderation
 * @property integer $ip
 * @property integer $watch
 * @property integer $section_id
 * @property integer $author_id
 */
class Text extends \yii\db\ActiveRecord
{
    /**
     * Publish status
     */
    const STATUS_PUBLISH = 1;

    /**
     * Unpublish status
     */
    const STATUS_UNPUBLISH = 0;

    /**
     * Default section id
     */
    const DEFAULT_SECTION = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'text';
    }

    /**
     * Behaviors
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['date'],
                ],
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'author_id',
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['moderation', 'default', 'value' => self::STATUS_UNPUBLISH],
            ['section_id', 'default', 'value' => self::DEFAULT_SECTION],
            [['moderation', 'ip', 'section_id'], 'required'],
            [['date', 'rating', 'moderation', 'ip', 'watch', 'section_id', 'author_id'], 'integer'],
            ['title', 'required', 'message' => 'Исемне языгыз'],
            ['text', 'required', 'message' => 'Текстны языгыз'],
            [['text'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['section_id'], 'exist', 'skipOnError' => true, 'targetClass' => Section::className(), 'targetAttribute' => ['section_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'rating' => 'Rating',
            'title' => 'Исем',
            'text' => 'Текст',
            'moderation' => 'Moderation',
            'ip' => 'Ip',
            'watch' => 'Watch',
            'section_id' => 'Бүлек',
            'author_id' => 'Author ID',
        ];
    }

    public function getCommentsCount()
    {
        return Comments::find()->where(['text_id' => $this->id])->count();
    }
}

controllers/TextController.php
<?php

namespace app\controllers;

use app\models\Section;
use Yii;
use app\models\Text;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use app\models\Comments;
use app\models\ContactForm;
use app\models\Watch;
use app\models\VoteText;
use yii\helpers\Url;

class TextController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Text::find()->where(['moderation' => Text::STATUS_PUBLISH])->orderBy('date DESC'),
            'pagination' => [
                'pageSize' => 10,
                'defaultPageSize' => 10,
            ],
        ]);
        return $this->render('index', [
            'listDataProvider' => $dataProvider
        ]);
    }

    public function actionView($id)
    {
        $model = Text::find()->where([
            'id' => $id,
            'moderation' => Text::STATUS_PUBLISH
        ])->one();

        if ($model === null) {
            throw new NotFoundHttpException;
        }

        // TODO Сервиска кучерергэ
        $model->updateCounters(['watch' => 1]);

        $modelComments = new Comments();
        $modelComments->text_id = $model->id;
        $modelComments->date = time();
        $modelComments->user_id = Yii::$app->user->getId();
        if ($modelComments->load(Yii::$app->request->post()) && $modelComments->save()) {
            return $this->refresh();
        }

        $allComments = Comments::find()->with('user')->where(['text_id' => $id])->all();

        return $this->render('view', [
            'model' => $model,
            'modelComments' => $modelComments,
            'comments' => $allComments,
        ]);
    }

    /**
     *
     * Add vote to text
     *
     * @param string $type
     * @param int $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionVote(string $type, int $id)
    {
        $user = Yii::$app->user->getId();

        if (Yii::$app->user->isGuest) {
            return $this->render('info', [
                'alert' => 'warning',
                'message' => 'Бары тик <a href=' . Url::to(['/user/user/signup']) . ' class="alert-link">теркәлгән</a>
                һәм <a href="' . Url::to(['/user/user/login']) . '" class="alert-link">авторизация</a> үткән кулланучылар
                 гына тавыш бирә ала.',
                'title' => 'Бары тик теркәлгән һәм авторизация үткән кулланучылар гына тавыш бирә ала',
            ]);
        }

        $model = Text::find()->where([
            'id' => $id,
            'moderation' => Text::STATUS_PUBLISH
        ])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        $vote = VoteText::find()->where([
            'text_id' => $id,
            'user_id' => $user,
        ])->one();


        if ($vote === null) {
            $newVote = new VoteText();
            $newVote->text_id = $id;
            $newVote->user_id = $user;
            $newVote->save();

            $update = (($type == 'rox') ? 1 : (($type == 'sox') ? '-1' : 0));
            $model->updateCounters(['rating' => $update]);
        } else {
            return $this->render('info', [
                'alert' => 'warning',
                'message' => 'Сез инде бу текстка тавыш бирдегез!'
            ]);
        }

        return $this->redirect(['text/view', 'id' => $id]);

    }

    public function actionOrder()
    {
        throw new NotFoundHttpException;
        return $this->render('order');
    }

    public function actionAdd()
    {
        $model = new Text();

        $sections = Section::find()->all();
        $sections = ArrayHelper::map($sections, 'id', 'name');

        $ip = ip2long(Yii::$app->getRequest()->getUserIP());
        $model->ip = $ip;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->render('info', [
                'alert' => 'success',
                'message' => 'Сезнең текст модерацияга жибәрелде. Модерация уткәч сайтта чыгыр. Рәхмәт!'
            ]);
        }

        return $this->render('add',[
            'model' => $model,
            'section' => $sections
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSitemap()
    {
        return $this->render('sitemap', [
            'text' => Text::find()->where(['moderation' => Text::STATUS_PUBLISH])->all()
        ]);
    }

}

views/text/_list.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\StringHelper;
use yii\helpers\Url;

?>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 box">
    <div class="row">
        <a href="<?= Url::toRoute(['text/view', 'id' => $model->id]) ?>" class="title"><?= Html::encode($model->title) ?></a>
        <div class="date"><?= Yii::$app->formatter->asDate($model->date) ?></div>
        <div class="text"><?= StringHelper::truncate(HtmlPurifier::process($model->text), 600, '...') ?></div>
        <div class="items">
            <a href="<?= Url::toRoute(['text/view', 'id' => $model->id]) ?>#comments" class="comments">фикерләр (<?= $model->getCommentsCount() ?>)</a>
            <a href="<?= Url::toRoute(['text/view', 'id' => $model->id]) ?>" class="link">тулаем</a>
        </div>
    </div>
</div>

views/text/about.php
<?php

$this->title = 'Сайт турында' . Yii::$app->name;
?>

<h2>Сайт турында</h2>
<p>Сәлам. Сайт үзендә бик күп татарча сочинения һәм иншалар туплаган. Аны теләсә кем укый һәм шуннан чыгып үзенә инша яки сочинения яза ала.
    Сайтка кергән өчен рәхмәт. Ошый икән, башкаларга да киңәш ит!</p>
<p>VK челтәрендә безнең <a href="https://vk.com/insharu" target="_blank" rel="nofollow">төркем</a>.</p>

views/text/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Text */
/* @var $form ActiveForm */

$this->title = 'Өстәү' . Yii::$app->name;
?>
<div class="add">
    <h2>Өстәү</h2>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title') ?>
    <?= $form->field($model, 'text')->textarea(['rows' => 20]) ?>

    <div class="form-group">
        <?= Html::submitButton('Өстәү', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- test -->

views/text/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Элемтә' . Yii::$app->name;
?>
<h2>Элемтә</h2>

<?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

<?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

<?= $form->field($model, 'email') ?>

<?= $form->field($model, 'subject') ?>

<?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
]) ?>

    <div class="form-group">
        <?= Html::submitButton('Жибэру', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/text/index.php
<?php
/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'Баш бит' . Yii::$app->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => 'Интернет челтәрендәге беренче инашалар сайты. Сез бездә иншалар, татарча сочинениялар, язмалар, юлъязмалар һ.б. таба аласыз. Рәхим итегез.',
]);

echo ListView::widget([
    'dataProvider' => $listDataProvider,
    'itemView' => '_list',
    'summary' => '',
    'pager' => [
        'firstPageLabel' => 'беренче',
        'lastPageLabel' => 'соңгы',
    ],

]);
?>

views/text/info.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $message string */
/* @var $title string */
/* @var $alert string type of alert: success, info, warning, danger */

$this->title = !empty($title) ? $title : $message;
$this->title .= Yii::$app->name;

?>
<div class="alert alert-<?= $alert ?>" role="alert"><?= $message ?></div>

views/text/order.php
<?php

$this->title = 'Заказ бирү' . Yii::$app->name;
?>

<h2>Заказ бирү</h2>

views/text/sitemap.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Барлык иншалар, сочинениялар' . Yii::$app->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => 'Барлык иншалар, сочинениялар бер биттә.',
]);

?>

<div class="text">
<h1>Иншалар, татарча сочинениялар</h1>

<?php foreach ($text as $value): ?>

    <div class="block">
    <a  href="<?= Url::toRoute(['text/view', 'id' => $value->id]) ?>" class="sub_title">
        <?= Html::encode($value->title) ?>
    </a>
    </div>

<?php endforeach; ?>
</div>

views/text/view.php
<?php
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $modelComments app\models\Comments */
/* @var $form ActiveForm */
/* @var $comments app\models\Comments */

$this->title = $model->title . Yii::$app->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->title,
]);
?>

<div class="text">
    <h1><!-- <a href="/section/1/">Инша</a> / --><?= Html::encode($model->title) ?></h1>

    <div class="date"><?= Yii::$app->formatter->asDate($model->date) ?></div>

    <div class="view"><?= nl2br(Html::encode($model->text)) ?></div>

    <div class="block">
        Бу язма <b> <?= $model->rating ?> </b> кешегә булышты. Ә сиңа ?
        <a href="<?= Url::to(['text/vote', 'type' => 'rox', 'id' => $model->id]) ?>">булышты</a> |
        <a href="<?= Url::to(['text/vote', 'type' => 'sox', 'id' => $model->id]) ?>">булышмады</a><br>
        Язманы <b> <?= $model->watch ?> </b> кеше укыды</p>
    </div>

</div>

<div class="comments">
    <div class="name"><a name="comments"></a>фикерләр (<?= count($comments) ?>)</div>

    <?php if (empty($comments)): ?>
        <p>Кызганычка каршы бу бүлектә әлегә фикерләр юк</p>
    <?php else : ?>
        <?php foreach ($comments as $comment): ?>
            <div class="user"><a name="comments<?= $comment->id ?>"></a><?= $comment->user['username'] ?? 'Аноним' ?></div>
            <div class="date"><?= Yii::$app->formatter->asTime($comment->date) ?></div>
            <p><?= Html::encode($comment->text) ?></p>
        <?php endforeach; ?>
    <?php endif; ?>

   <?php if (\Yii::$app->user->isGuest): ?>
       <div class="comments-registration alert alert-info" role="alert">
           Бары тик <a href="<?= Url::to(['/user/user/signup']) ?>" class="alert-link">теркәлгән</a>
           һәм <a href="<?= Url::to(['/user/user/login']) ?>" class="alert-link">авторизация</a> үткән кулланучылар гына фикер калдыра ала.
       </div>
   <?php else: ?>

       <div class="views-comment">

           <?php $form = ActiveForm::begin(); ?>

           <?= $form->field($modelComments, 'text')->textarea(['rows' => 5]) ?>

           <div class="form-group">
               <?= Html::submitButton('Өстәү', ['class' => 'btn btn-primary']) ?>
           </div>
           <?php ActiveForm::end(); ?>

       </div><!-- views-comment -->

   <?php endif; ?>
</div>