models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property integer $date
 * @property string $title
 * @property string $text
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'integer'],
            [['text'], 'string'],
            [['title'], 'string', 'max' => 150],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'title' => 'Title',
            'text' => 'Text',
        ];
    }
}

controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\News;
use yii\data\ActiveDataProvider;

class NewsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => News::find()->orderBy('id DESC'),
            'pagination' => [
                'pageSize' => 5,
                'defaultPageSize' => 5,
            ],
        ]);

        return $this->render('index',[
            'news' => $dataProvider
        ]);
    }

    public function actionView(int $id)
    {
        $news = News::find()->where(['id' => $id])->one();

        return $this->render('view', [
           'model' => $news
        ]);
    }

}

views/news/_list.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\StringHelper;
use yii\helpers\Url;

?>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 box">
    <div class="row">
        <a href="<?= Url::toRoute(['news/view', 'id' => $model->id]) ?>" class="title"><?= Html::encode($model->title) ?></a>
        <div class="date"><?= Yii::$app->formatter->asDate($model->date) ?></div>
        <div class="text"><?= StringHelper::truncate(HtmlPurifier::process($model->text), 200, '...') ?></div>
        <div class="items">
            <!--<a href="<?/*= Url::toRoute(['text/view', 'id' => $model->id]) */?>#comments" class="comments">фикерләр (<?/*= $model->getCommentsCount() */?>)</a>-->
            <a href="<?= Url::toRoute(['news/view', 'id' => $model->id]) ?>" class="link">тулаем</a>
        </div>
    </div>
</div>

views/news/index.php
<?php
/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'Яңалыклар' . Yii::$app->name;
?>

<h2>Яңалыклар</h2>

<?= ListView::widget([
    'dataProvider' => $news,
    'itemView' => '_list',
    'summary' => '',
    'pager' => [
        'firstPageLabel' => 'беренче',
        'lastPageLabel' => 'соңгы',
    ],

]);

views/news/view.php
<?php

use yii\helpers\Html;

$this->title = $model->title . Yii::$app->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->title,
]);
?>

<div class="text">

    <h1><?= Html::encode($model->title) ?></h1>

<div class="date"><?= Yii::$app->formatter->asDate($model->date) ?></div>

<div class="view"><?= Html::encode($model->text) ?></div>


</div>